stages:
  - build
  - test

build:
  image: docker
  services:
     - docker:dind
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE || true
    - docker build --cache-from $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  image: carelessfinch/ubuntu-tools
  services:
    - $CI_REGISTRY_IMAGE
  stage: test
  script:
    - chmod +x Admin/run.sh
    - ./Admin/run.sh
